### ISSUE TITLE
Getting the token doesn't work

### ISSUE THREAD

**Issue by fwieringen** [Maarten234/Enphase-Envoy-D7.0.X-node-red#1]
First of all, thank you so much for this flow. My Envoy was updated to v7 this morning and all my Domotics Node Red flows stopped working...

I added your flow and it almost worked directly out of the box. 

Getting the token didn't work, so I manually set msg.token in the "Obtain session ID" block. Is there anything I can do to help dubugging the getting the token part? When I manually requested the token, I also needed to provide a site name.

**Comment by Maarten234** [comment]
Hi Floris, 

I'm not able to reproduce the issue you experienced. Did you provide your credentials to node "Login credentials". In this node you should provide the credentials you needed to provide yourself when obtaining a token via website https://entrez.enphaseenergy.com/

**Comment by fwieringen** [comment]
I added some Debug nodes. I get a 401 error after the entrez.enphaseenergy.com node. Just a typo in the password #facepalm
